[package]
name = "compare_by_address_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
by_address = "1.0.4"
syn = "1.0"
quote = "1.0"

[lib]
proc-macro = true